### ISSUE TITLE
Out-of-date references to free credits

### ISSUE THREAD

**Issue by oktools** [lbryio/lbry.io#106]
New and prospective users are currently told by the site that they can get free credits in the quickstart tutorial and at seemingly at least one place that suggests users go to the slack channel to get them, which some interpret as "go there and ask."

Apart from creating a jilting initial experience in the quickstart, where users cannot work through the steps because they have no credits, the slack participants seem to be answering the same question each day as to "Is this the place I get my credits?"

I will be happy to do some editing and send a pull request. I assume this is something that is already being thought about and possibly addressed, so I'm opening it as an issue to get feedback and comments.

**Comment by kauffj** [comment]
I decided to quietly turn this back on and reduce the reward some. We'll see how it goes.
