### ISSUE TITLE
Referral link incorrect

### ISSUE THREAD

**Issue by AndreasGassmann** [lbryio/lbry.io#111]
I just signed up for early access and the referral link that was shown on the page was wrong.

<img width="752" alt="referral" src="https://cloud.githubusercontent.com/assets/680814/26514982/599d5706-4276-11e7-8af8-774c9d1e1299.png">

The one in the email was ok.

**Comment by chadfurman** [comment]
Same.

**Comment by kauffj** [comment]
We're moving this into the app.
