### ISSUE TITLE
Quickstart Credits step get an Extraneous params: access_token error 

### ISSUE THREAD

**Issue by 7sDream** [lbryio/lbry.io#112]
Already loigin use Github account, then click send button, I got an error:

![](http://rikka-10066868.image.myqcloud.com/358fa47c-3860-4f6c-8d90-425e863b0dcb.png)

It's a server bug or browser bug?

**Comment by AndreasGassmann** [comment]
I had the same problem and reported it a couple days ago.

<img width="512" alt="screen_shot_2017-05-26_at_23 31 22_1024" src="https://cloud.githubusercontent.com/assets/680814/26545645/ae620f38-4466-11e7-876a-97bfb919e850.png">

**Comment by Invertex** [comment]
Same issue as well. Sounds like LBRY needs to update how it's communicating with Github auth.

**Comment by lyoshenka** [comment]
I believe I fixed this. Please give it another try and reopen this if its still happening.

**Comment by 7sDream** [comment]
@lyoshenka 

Yes, It works now, and I can get the credits.But there is still a small bug in the success message:

![image](https://cloud.githubusercontent.com/assets/7822577/26567258/63e163b6-452c-11e7-9ba4-f6e1c9974132.png)

The [undefined] word may be due to  a typo in Javascript  or something.
