### ISSUE TITLE
Can't check referrals info in website

### ISSUE THREAD

**Issue by 7sDream** [lbryio/lbry.io#113]
Can't get referral info when input my register email address, instead I got an error:

```
We were unable to add you to the wait list. Received error "Tester exists. Please use the update method.". Please contact josh@lbry.io if you think this is a mistake.
```

Screenshot:

![image](https://cloud.githubusercontent.com/assets/7822577/26558457/81ab522c-44db-11e7-80ec-dd525bdccf01.png)

Click the the link in email (content as below, sent by jeremy[AT]lbry.io when first time join the list) get the same error.

```
You can check your status and referals at any time by clicking here.  <--- The Link
```

**Comment by jameshaswon** [comment]
I am also receiving this bug when clicking on the link that should be showing me my referral statistics.

**Comment by tzarebczan** [comment]
Thanks for reporting, we'll look into it.

**Comment by lyoshenka** [comment]
I'm in the process of revamping the referral setup (which I know has been somewhat neglected recently). So it will work :soon:  :tm:

**Comment by hakunin** [comment]
How soon? :)

**Comment by tzarebczan** [comment]
Is a link not working for you?

**Comment by hakunin** [comment]
Yep, when signing up for waitlist, I get this:
![screenshot 2017-07-04 14 22 49](https://user-images.githubusercontent.com/65846/27830844-7bfb4680-60c8-11e7-91df-adce730fc6b7.png)

**Comment by hakunin** [comment]
The link you sent me via email to check my refferal status doesn't work properly either. 
https://www.dropbox.com/s/g1y8fho296nxtuz/Screenshot%202017-07-04%2015.16.17.png?dl=0
It might be a good idea to start doing QA and writing automated tests..

**Comment by tzarebczan** [comment]
It was working up until yesterday, we are looking into it. Thanks for the heads up.

**Comment by hakunin** [comment]
Still, if you can - think about getting an automated test suite and a couple of QA people. Its worth it.

**Comment by tzarebczan** [comment]
Thanks, we are looking into it :)

**Comment by hakunin** [comment]
Another thing: Reddit user says the reward was reduced to 2.5 LBC while the site still says 10.
https://www.reddit.com/r/lbry/comments/6io05d/lbry_ref_got_reduced_to_25_coins/

**Comment by kauffj** [comment]
We're moving this into the app.

You can download LBRY at lbry.io/get
