### ISSUE TITLE
Insufficient funds when trying to receive credits

### ISSUE THREAD

**Issue by CodeFalling** [lbryio/lbry.io#114]
I am a new user and try to receive credits at https://lbry.io/quickstart/credits#new-developer to `bLUG5rXzBrXdCFecH9PhHLV2vXkYML9X6d`

But got a `-6: Insufficient funds` error.

![image](https://cloud.githubusercontent.com/assets/5436704/26622373/c2b393b4-461c-11e7-8068-7df75cfc62e7.png)

What should I do?

**Comment by kauffj** [comment]
This should be fixed.
