### ISSUE TITLE
How to view lbry://what links exactly?

### ISSUE THREAD

**Issue by techtonik** [lbryio/lbry.io#115]
I am running a command line daemon. What is the procedure to view and search lbry://what content for me?

**Comment by kauffj** [comment]
1. `./lbrynet-cli resolve uri=lbry://what`
1. `./lbrynet-cli get uri=lbry://what`

**Comment by kauffj** [comment]
you can also omit `lbry://`

**Comment by techtonik** [comment]
What about browser?

**Comment by tzarebczan** [comment]
You need to view them via the lbry app,not browser. For free and public claims, you can use https://spee.ch

**Comment by techtonik** [comment]
Is it possible to create some browser plugin (Electron doesn't support Vista)?

**Comment by tzarebczan** [comment]
The first incarnation of our app was browser based access. I guess it's possible to build something like it. You can also upgrade from Vista to Windows 10 for free no?

**Comment by techtonik** [comment]
> You can also upgrade from Vista to Windows 10 for free no?
No.
