### ISSUE TITLE
Add post-commit hook to clear GitHub cache on releases

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.io#135]

**Comment by kauffj** [comment]
When pushing a new release, the download links can take up to an hour to update.

**Comment by tzarebczan** [comment]
Hook to refresh links was added to lbry.io/xxxxxx (See internal PR documetnation)

**Comment by kauffj** [comment]
lbry.io is open source so it's not really a secret :)

@lyoshenka said he wasn't concerned with abuse of the ability to clear the cache
