### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by sonatagreen** [lbryio/lbry.io#18]
[posts/faq/is-lbry-open-source.md](https://github.com/lbryio/lbry.io/blob/master/posts/faq/is-lbry-open-source.md) says that the website, and therefore this repository, is "open source".

However, unlike in the code repositories, no specific license seems to be specified; there's no LICENSE file in the repo, and no copyright/license statement that I've found on the website.

As a matter of open source best practices, this should be made explicit somewhere. Simply saying "open source" isn't enough, because there are multiple different open source licenses, and they're not fully equivalent.

**Comment by kauffj** [comment]
Good catch! I think MIT license is the best license (most open), but I think we'd want to amend it to be clear it does not license all of the content, just the code.

**Comment by lyoshenka** [comment]
fixed
