### ISSUE TITLE
Evolution of backup KB articles

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.io#211]
1. Checkout new back-up feature in app. Assess any changes required here.
1. Determine if 1 or 2 articles needed for KB
1. Write/update both.
1. Link one or both from app.

**Comment by kauffj** [comment]
@tzarebczan text revised in 6e61a9f.

We will keep backing up as two separate articles. In this case, following changes should be made to existing wallet backup article:

- Drop the references to the old wallet (put this in a separate article if we need to keep it).
- Have article reference that you can find the path in the app. If we want to keep how to find it manually, put this in separate/bottom section.
- Include better actual best practices for how to back it up. Assume people know less about how to do this.
- Possibly include a screenshot of how to get to the page that shows you your path in the app?

You should also try cleaning up the other "How to Backup" article.

**Comment by MSFTserver** [comment]
was it meant for the backup link to be greyed out if im not verified? i noticed this upon a fresh install

**Comment by tzarebczan** [comment]
It's greyed out if there are no transactions on the account. I mentioned this to @kauffj and he's open to changing it in the future.

**Comment by tzarebczan** [comment]
The first stab is here, let me know what you think: https://github.com/lbryio/lbry.io/pull/219

**Comment by tzarebczan** [comment]
Completed in https://github.com/lbryio/lbry.io/pull/219
