### ISSUE TITLE
Talk about scheduling: Allow creation of new users via lbry.io

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry.io#215]
@kauffj commented on [Mon Jul 31 2017](https://github.com/lbryio/internal-apis/issues/39)

Pages like https://lbry.io/android prompt users to enter an email, which currently puts them directly on Mailgun, rather than in the API database.

This will require updates to lbry.io, but I felt it was better placed in this repo.

---

@lyoshenka commented on [Fri Sep 01 2017](https://github.com/lbryio/internal-apis/issues/39#issuecomment-326710490)

I'm moving this to lbryio repo because the API already has endpoints for everything you need: `/user/new` and `/user_email/new`

**Comment by tzarebczan** [comment]
@lyoshenka  - when users go to https://lbry.io/android and enter their email, where is it stored? You don't get anything in terms of a confirmation either, just takes you back to the page.
