### ISSUE TITLE
Add gnome-keyring expectation to startup troubleshooting page

### ISSUE THREAD

**Issue by eriknelson** [lbryio/lbry.io#225]
I have a few workstations that run a minimal i3 env without `gnome-keyring` installed and enabled; it made the client hang without explanation: [issue](https://github.com/lbryio/lbry-app/issues/572). Looks like there are a number of other people who have run into this problem. Would be good to add the observed error and a section on why that's happening to the startup troubleshooting page.

**Comment by tzarebczan** [comment]
We already have it mentioned on the startup page:
https://lbry.io/faq/startup-troubleshooting

Currently, LBRY requires an authorization token to be generated using the keytar libraries. Please ensure libsecret and keytar are installed. On some distributions, LBRY won't run unless gnome keyring is also installed/operational. See GitHub issue for more information. If you get a GLIBCXX_3.4.2 error, please see this issue.
