### ISSUE TITLE
Enhancements to /get

### ISSUE THREAD

**Issue by finer9** [lbryio/lbry.io#234]
- Reilly video of app use
- Version # 
- Size of download

<img width="787" alt="adobe" src="https://user-images.githubusercontent.com/16390156/31034321-8f4eb43a-a531-11e7-8fcf-feb1f03dec3a.PNG">

**Comment by finer9** [comment]
@kauffj how do I programmatically get the version and file size of the current release?

**Comment by finer9** [comment]
@reillysmith add that gif when ready, here

**Comment by finer9** [comment]
Hey divas anyone want to help me?? :p

**Comment by finer9** [comment]
GitHub::get('/repos/lbryio/lbry-app/releases/latest') - @kauffj can you write me a two functions - one that outputs the version and one that outputs the file size?  Just simple text output I can call.  @lyoshenka pretty please?

**Comment by kauffj** [comment]
Done and live.

This line is where the new information is being rendered:

https://github.com/lbryio/lbry.io/blob/master/view/template/download/get.php#L30

**Comment by tzarebczan** [comment]
The new downloads page looks great!
