### ISSUE TITLE
Update references to Slack

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.io#242]
It appears a number still exist, even though the navigation has been corrected:

https://github.com/lbryio/lbry.io/search?utf8=%E2%9C%93&q=slack&type=

**Comment by tzarebczan** [comment]
Yep, was waiting for the chat.lbry.io url to work. Will update these shortly.

**Comment by tzarebczan** [comment]
@kauffj should be all set. There are still some references to Slack in the code / old bounties.
