### ISSUE TITLE
Update website homepage etc.

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry.io#246]
@hackrush01 commented on [Wed Oct 25 2017](https://github.com/lbryio/internal-issues/issues/51)

The app has come a long way in the past few weeks, the homepage image should be updated to reflect the same(a slider gallery could be even better, I guess). Possibly low priority, and I was unsure where to file issue, so I opened it here.

---

@kauffj commented on [Wed Oct 25 2017](https://github.com/lbryio/internal-issues/issues/51#issuecomment-339441431)

@hackrush01 please open in lbryio/lbry.io

**Comment by etisdew** [comment]
at 1366 * 768 native resolution and firefox dev, layout makes header and footer redundantly create scrolling. Its very close to looking like an SPA by a very narrow margin.

**Comment by tzarebczan** [comment]
@etisdew can you please make a new issue with screenshots for this?
