### ISSUE TITLE
Consider creating Publisher or Creator FAQ category

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.io#254]
Inspired by https://github.com/lbryio/lbry.io/pull/253, which I ended up putting other Other. I think at least 3 questions could go in this category, so it might make sense to start one.

**Comment by LavRadis** [comment]
I'm interested in contributing to this FAQ. Tom let me know if it's ok and give me some guidelines.

**Comment by tzarebczan** [comment]
@kauffj we have https://lbry.io/faq/how-to-publish

Did you want something more high level which branches off into that?

**Comment by kauffj** [comment]
@LavRadis @tzarebczan this ticket is just for a new category.

I think `how-to-publish`, `community-top-bids`, and `make-money` (which should prob be renamed) could all be clustered in the same category for Publishers, along with a new article or two (like at least one about YouTube sync!).

**Comment by tzarebczan** [comment]
Ah, got it now. Yup makes sense.

**Comment by tzarebczan** [comment]
Completed in https://github.com/lbryio/lbry.io/pull/276
