### ISSUE TITLE
Shapeshift FAQ

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry.io#255]

**Comment by kauffj** [comment]
Please give this article a slug of `shapeshift`.

**Comment by kauffj** [comment]
FAQ should cover:

- Shifts are handled by ShapeShift. We don't handle funds and funds aren't coming from us.
- Some kind of disclaimer that puts ShapeShift as responsible as possible.
- Mention that ShapeShift charges fees (link to their materials on this).
- Cover that once you've finished the shift, there's not really a record of it. Once the app sees the funds hit your wallet, it'll update, but the app won't display pending shifts.
- Link at some point to the more general article on how to acquire LBC
- Possibly the first FAQ article to show app pics?!?!

**Comment by kauffj** [comment]
@seanyesmunt you're encouraged to add anything here that may be important to cover about this feature. In particular try to think of things that a curious user might want to know, or that a user who is confused or uncertain about this feature might want to know and/or be re-assured about.

**Comment by seanyesmunt** [comment]
I'll try to think of other stuff we can include. I like the idea of including pictures of how a successful shift will look.

**Comment by lyoshenka** [comment]
Is it true that there's no record of the shift? Can we at least show the
user a url to see the shift, or a shift id. I think shapeshift has that.

**Comment by seanyesmunt** [comment]
Yes, in the current implementation there is a link to the shapeshift status
page
