### ISSUE TITLE
RFC - issue #246

### ISSUE THREAD

**Issue by etisdew** [lbryio/lbry.io#257]
*[Source](https://github.com/lbryio/lbry.io/issues/246)*
![image](https://user-images.githubusercontent.com/26851121/33361386-bb23b5bc-d48c-11e7-8c73-e5c09aac41bd.png)
This displays perfectly in fullscreen (via f11) however feels redundant considering it creates a scroll in of itself by including a footer. Would you stylistically appreciate the single page layout? If you highlight the image and note how it perfectly fills all of the screen space without leaving room for the browser components.

**Comment by etisdew** [comment]
Would i be going too far out on a limb calling the footer header and leaving it on the bottom?

**Comment by lyoshenka** [comment]
good point. I removed the footer. thanks for pointing this out. take a look at https://lbry.io/faq/tips
