### ISSUE TITLE
Make download button on lbry.io homepage actually download

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.io#258]
1. Create a partial, `download/_button.php` that will render just a download button (the button that currently exists on `get.php`).
2. Use `DownloadActions::prepareButtonPartial` to prevent duplication of code re: OS detection
3. If the button is rendered for a request from an OS we do not support, have the button link to `/get` instead (which will explain it is not available on that OS and collect their email).
4. Do include the fine text below the button (the build timestamp).
5. Refactor `get.php` to use this partial as appropriate.

**Comment by FUNKePILLs** [comment]
On it.

**Comment by kauffj** [comment]
@FUNKePILLs how is this coming?

**Comment by Jeremy1026** [comment]
Pull request submitted for this issue - https://github.com/lbryio/lbry.io/pull/353

**Comment by xorgy** [comment]
On the surface this looks like a good idea, but it should probably still be a separate page for Linux users. Ubuntu may have a majority, but it'll be misleading for users of other distributions if they click to download and it just gives them a deb.

**Comment by kauffj** [comment]
That is a very good point @xorgy! Is there a browser-based way of detecting `.deb` packaging support? If not, I agree that we should send to the full page on Linux.

**Comment by xorgy** [comment]
@kauffj It doesn't seem like there is any reliable way to detect that, so I think a redirect is necessary for now.

**Comment by Jeremy1026** [comment]
My pull request handles non-Debian distros in this manner. If there isn't a valid match for a release in GitHub the button will link to /get instead of providing a direct download to the .deb. Tested with a CentOS user-agent string of `Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.24) Gecko/20111109 CentOS/3.6.24-3.el6.centos Firefox/47.0`

**Comment by xorgy** [comment]
@Jeremy1026 Interesting that Firefox on CentOS has a special UA, this is my chrome on ArchLinux: 
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
```

**Comment by Jeremy1026** [comment]
I’ll pop them in as a test to see what happens, but I *think* that should work as expected.
