### ISSUE TITLE
Figure out a way to sync docs/kb across repos

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.io#280]
There's good content here: https://github.com/lbryio/lbryschema/tree/master/docs

At least some of this should also be on lbry.io.

**Comment by tzarebczan** [comment]
@kauffj should we close this as these docs will now live on lbry.tech?

**Comment by kauffj** [comment]
I think this question still remains, but could now live in lbry.tech.

It's not clear that all technical documentation should live in the lbry.tech repo. In some cases, it may make sense for the documentation to live in the project repo and just be imported/displayed by lbry.tech.

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/lbry.tech #43](https://github.com/lbryio/lbry.tech/issues/43) via [**ZenHub**](https://www.zenhub.com/)
