### ISSUE TITLE
Create YouTube sync FAQ

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.io#281]
This will explain users how the sync process works and what the requirements are.

It will be linked from the app.

Please create this at lbry.io/faq/youtube

**Comment by ykris45** [comment]
If your YouTube account has more than 10 videos and 30K views and you are not verified after restarting LBRY(close completely from tray), please contact hello@lbry.io with your YT channel name and LBRY connected email. (The requirements of yt sync)
