### ISSUE TITLE
Add support for blog tags

### ISSUE THREAD

**Issue by reillysmith** [lbryio/lbry.io#290]
1. Add support for defining multiple tags in the FrontMatter metadata of a blog post. The definition should look like this:

`tags: tag1, tag2`

2. Add a route ( `/news/tag/{tag}`) and handler for displaying all blog posts with a tag. This may be a new handler or just a modification to `ContentActions::executeNews`. Use `Post::filter` to filter for posts with a tag (`ContentActions::executeFaq` has a good example of this).

3. Modify the view to indicate it is showing just posts with a tag. 

4. Update the view for an individual blog post to show it's tags.

**Comment by kauffj** [comment]
Do you see this as different from "categories" in a traditional blog context?

(Categories = pick one and only one, as opposed to tags, which is pick as many as you like)

**Comment by Feanor78** [comment]
It would be better to have tags so that content could appear in all the appropriate buckets - sometimes development and news will overlap, etc.

Whatever the easiest technical solution to make it work like the "bounties' page is, I'm in favor of that :)
