### ISSUE TITLE
Implement "categories" functionality for "news" posts

### ISSUE THREAD

**Issue by Feanor78** [lbryio/lbry.io#291]
Allow blog posts in the "news" section to be categorized like posts in the "bounty" section (https://lbry.io/bounty) and create RSS subscriptions/feeds for each category

**Comment by tzarebczan** [comment]
@Feanor78 is this the same as https://github.com/lbryio/lbry.io/issues/290 ? Maybe expand on that one

**Comment by Feanor78** [comment]
Yes, pretty much the same.

**Comment by kauffj** [comment]
Duplicate of #290
