### ISSUE TITLE
Fix render of github release notes(markdown) on roadmap

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.io#292]
Lbry.io/roadmap does not process markdown correctly which affects the release notes sections.

**Comment by vfioox** [comment]
What is the problem specifically? Is this issue already resolved?

**Comment by tzarebczan** [comment]
Take a look at https://Lbry.io/roadmap - it pulls from github and it doesn't convert the markdown parts into linkable URLs. Compare to the changelog on lbry-app

**Comment by maximest-pierre** [comment]
I have started debugging this issue, but it seems that the GitHub API returns do not include the PR's URL, only the number. I have attached a gist with one of the GitHub API calls body.
https://gist.github.com/maximest-pierre/96564036ef8c51dfbf25898b52d19e54

**Comment by tzarebczan** [comment]
We can fix the change log so it has the entire url (see some older entries on the app, they have the url). We'd want to convert that to a inline hyperlink on the pr/issue #.

**Comment by maximest-pierre** [comment]
So I tested on one of my repo and by adding the whole URL in markdown ```[#1](https://github.com/test/test)``` instead of just the number ```#1``` the API returns the placeholder and the link. This behavior is caused by the way that GitHub interacts with PR and issues number in their backend.

Example to repeat this finding:
curl command: ```curl -v https://api.github.com/repos/maximest-pierre/Release_test/releases/tags/1.0.0```
release URL: https://github.com/maximest-pierre/Release_test/releases/tag/1.0.0

**Comment by tzarebczan** [comment]
Thanks @maximest-pierre , I'll get these updated on the releases and changelog.

**Comment by tzarebczan** [comment]
@maximest-pierre will it support 2 links in 1 line like: https://github.com/lbryio/lbry-app/releases/tag/v0.19.1 ?

**Comment by maximest-pierre** [comment]
I am pretty sure it will support it.

**Comment by maximest-pierre** [comment]
It works on my computer but the links are not colorized correctly but they are there. I will look into this later today.

**Comment by tzarebczan** [comment]
@maximest-pierre I see that as well, thanks. 

@kauffj suggested we should be able to perform a regexp pass on the roadmap description content in order to build the URLs programmatically.  This would need to be done on both the lbry and lbry-app repos.  I'll have to get the lbry repo changelog / release notes updated as well because they used just the URL (i.e. Fixed unnecessarily verbose exchange rate error (https://github.com/lbryio/lbry/issues/984))

**Comment by kauffj** [comment]
Yes, @maximest-pierre I think a regexp pass on the GitHub descriptions is a preferable solution.

Note that a single URL structure works for both Issues and PRs. E.g.:

https://github.com/lbryio/lbry-app/issues/942

942 refers to a PR, but linking to it as an issue simply redirects. GitHub uses a single consistent numbering scheme for both issues and PRs.

**Comment by maximest-pierre** [comment]
Alright, I will draft something up soon.

**Comment by maximest-pierre** [comment]
So I ended up not using a regex for this but changing the media type of the GitHub request from json to json+html which gave me access to the raw HTML with the link. It is a simpler fix than using regex, I am still testing this fix and enabling a lot more stuff to the roadmap.

**Comment by tzarebczan** [comment]
Closing this, last issue noted in #347
