### ISSUE TITLE
FAQ to summarize / simplify LBRY's stance and role in censoring "bad" content

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.io#315]
Questions come up frequently about pirated, sensitive, illegal content and how LBRY plans to deal with it. 

The closest resource we have for this information is: https://lbry.io/what#combatting-the-ugly

A summarization/simplification of LBRY's stance and how it plans to combat that type of content should belong in a separate FAQ article.

**Comment by tzarebczan** [comment]
Questions to consider covering:

Q. What happens if I use LBRY to publish kiddie porn?

A. https://lbry.io/what#combatting-the-ugly

Q. What happens if I use LBRY to publish the secret scripture of the Church of Scientology, and their lawyers want to sue both me and you into oblivion?

A. We comply with the CDA / DMCA to the best our technology allows. We would not be responsible for this, regardless of it's legality. Of course, given they're the church of scientology, nothing is probably going to actually stop them from suing us ;)

You, however, would be fully liable if you used LBRY to break the law.

Q. What happens if someone uses LBRY to publish my copyrighted material and I want to force it down and/or sue them into oblivion?

A. Similar to the linked answer above. 

Q. What happens if I use LBRY to publish classified material?

A. Again, similar answers to above. Not that dissimilar from what if someone did all of these things via BitTorrent.

**Comment by tzarebczan** [comment]
@reillysmith would you want to take a stab at this one?

**Comment by tzarebczan** [comment]
Maybe @jsigwart wants to take a shot after she's done with meetups/campus :p

**Comment by jsigwart** [comment]
Yes, you can assign this one to me, @tzarebczan

**Comment by tzarebczan** [comment]
@jsigwart can't assign you for some reason, but will create an Asana task to track this.

**Comment by kauffj** [comment]
Was this finished?

**Comment by tzarebczan** [comment]
Being worked on here: https://docs.google.com/document/d/1TynBaUgxfaufdVWjZqRrbKMr3zMY6sHexWwgNokl4wU/edit

**Comment by jsigwart** [comment]
Going to add copy per Tom's request, "we should talk about the protocol/blockchain vs app in terms of censorship somewhere in this doc," but would love more eyes on the overall doc.

**Comment by jsigwart** [comment]
#388 pull request

**Comment by tzarebczan** [comment]
Closed in https://github.com/lbryio/lbry.io/pull/388
