### ISSUE TITLE
Create LBRY App basics FAQ

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.io#317]
FAQ would cover:
What is the purpose of having my email connected to LBRY?
What information is tied to the account?
What is a wallet and how do I find it?
Where do I find my LBC address?
Why is content downloaded to my PC?
How do I know if I'm sharing content properly?
Content fails to stream or download, what can I do?

Any other thoughts?

**Comment by seanyesmunt** [comment]
How do I ensure that my wallet is backed up?

**Comment by seanyesmunt** [comment]
Maybe not that specifically but something talking about wallet backups

**Comment by seanyesmunt** [comment]
Cool. Seems reasonable

**Comment by seanyesmunt** [comment]
Am I being tracked? Might be nice to talk about the basic analytics we take and how users can turn them off, which still needs to be implemented.

I guess that might be under: What info is tied to my account

**Comment by jsigwart** [comment]
Is this going to be integrated into the main FAQ page?

**Comment by tzarebczan** [comment]
Yes, just haven't had a chance to take a closer look to clean it up.

**Comment by tzarebczan** [comment]
Closed with https://github.com/lbryio/lbry.io/pull/322
