### ISSUE TITLE
Broken images on old blog posts

### ISSUE THREAD

**Issue by Feanor78** [lbryio/lbry.io#324]
It appears that a lot of images are broken on old blog posts, including the author slug image for Samuel Bryan. Some examples below, pulled from posts around [this one](https://lbry.io/news/mde-on-lbry):

![image](https://user-images.githubusercontent.com/13907896/35113888-049b9a5c-fc51-11e7-8b5b-0368b6f6261f.png)
![image](https://user-images.githubusercontent.com/13907896/35113906-0ebd233e-fc51-11e7-84ae-ca05397ac15c.png)
![image](https://user-images.githubusercontent.com/13907896/35113920-19455d4e-fc51-11e7-8fd8-e562fd38c547.png)
![image](https://user-images.githubusercontent.com/13907896/35113937-27304f72-fc51-11e7-843d-db839387cd50.png)

In some cases, the image started to load and then disappeared/showed up as the "broken image" placeholder.

**Comment by lyoshenka** [comment]
Try these steps. Do any of them help? https://zenguard.zendesk.com/hc/en-us/articles/204423722-Chrome-error-ERR-SPDY-PROTOCOL-ERROR-

**Comment by lyoshenka** [comment]
Also, are you running Avast Antivirus? Seems that may be causing problems: https://productforums.google.com/forum/#!topic/chrome/sfAqeo4hDy8

**Comment by Feanor78** [comment]
Did the above and it didn't fix it - can we put this in some kind of priority bucket? We're going to be sending a lot of traffic to the site soon and it doesn't look great with a bunch of broken images.

**Comment by lyoshenka** [comment]
im on it

**Comment by lyoshenka** [comment]
It's fixed. server was out of inodes:

https://www.ivankuznetsov.com/2010/02/no-space-left-on-device-running-out-of-inodes.html

**Comment by Feanor78** [comment]
Awesome, it all seems to be working now - thanks!
