### ISSUE TITLE
highlight hyperlinks on roadmap

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.io#347]
Continuation of https://github.com/lbryio/lbry.io/issues/292

The hyperlinks to prs/issues on https://lbry.io/roadmap are not highlighted as such

**Comment by maximest-pierre** [comment]
I will check this out during the afternoon.

**Comment by tzarebczan** [comment]
@maximest-pierre hmm, the underlines cut through/into some of the pr #'s...almost seems like they are misaligned. 
![2018-02-02_15-03-16](https://user-images.githubusercontent.com/8120721/35752546-5ddea8f4-082a-11e8-8b53-64a1754a8cf0.png)

**Comment by maximest-pierre** [comment]
without the highlighting, they seem to do that also. It might be the font.

**Comment by maximest-pierre** [comment]
![screenshot from 2018-02-02 15-57-38](https://user-images.githubusercontent.com/7928135/35754550-d7857596-0831-11e8-914c-4719b576ded1.png)

By changing the font from raleway to roboto seems to fix it.
