### ISSUE TITLE
YouTube Onboarding Stage 2

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.io#364]
The following changes need to happen to lbry.io to support our new YouTube onboarding campaign (currently located at lbry.io/yt2, but eventually moving to lbry.io/youtube):

### Basic Cleanup
- [x] Integrated into standard page set up and flow. Currently, this page is dumped in raw in `yt2.php`, rather than using `basic.php` as a layout. It should use `basic.php`.
- [ ] Move CSS into SCSS. `yt2.css` should be an SCSS file, and included the way we typically handle CSS.
- [x] The table displaying the credit amounts should pull the subscribed amounts and reward values from the endpoint `api.lbry.io/yt/reward_info`.

### Proper Flow
- [x] When a enters a channel name and selects claim now, they should be down two additional inputs, one asking for their email, and another labeled "YouTube URL or Channel ID".
- [ ] After all 3 values are provided, all are submitted to a lbry.io endpoint. If the user submitted a YouTube URL rather than a channel id, the URL should be stripped to just a channel id.
- [x] The lbry.io endpoint should then submit both these values api.lbry.io (see `LBRY.class.php`). The specific endpoint to use is `api.lbry.io/yt/new`. E.g. `api.lbry.io/yt/new?email=foo@bar.com&desired_lbry_channel_name=@thebestchannel&youtube_channel_id=abcdef123`
- [x] The response to this URL call will include a property called `status_token`. The user should be redirected back to a new page, `/youtube/<status_token>`.

### Status Page
- [x] This page should take the status token from the URL and call `api.lbry.io/yt/status?status_token=xxx` to retrieve the status of a current sync process.
- [x] Display the email, channel name, sync queue spot, and expected LBC returned by this URL. 
- [ ] If not yet agreed to sync, it should include a button to initiate the process.

**Comment by reillysmith** [comment]
> When a enters a channel name and selects claim now, they should be down two additional inputs, one asking for their email, and another labeled "YouTube URL or Channel ID".

Why is this now a manual input? Am I reading this incorrectly? This should still be a read-only auth from their logged in Google account.

**Comment by kauffj** [comment]
@reillysmith The plan is to use the form as a lead-gen tool prior to auth (expecting someone to auth the sync on a first visit is asking a lot IMO). Not 100% sold on this approach though. Message me on Slack to discuss further.

**Comment by nikooo777** [comment]
Did you have a discussion regarding this? 
Can you update me or can we have a call together?
I think that the process should not allow anything else than specifying the email and the channel name, however authenticating with youtube should be done together. Why give space for second thoughts?

**Comment by kauffj** [comment]
Remaining work to be done is now in https://github.com/lbryio/lbry.io/issues/412
