### ISSUE TITLE
Add Acceptable Use Policy to Website

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry.io#368]
Review first draft, get sign-off, then add page.

**Comment by kauffj** [comment]
I think the proper place for this is the FAQ. So all that needs to be done for this is to migrate [this](https://docs.google.com/document/d/1qbkjMtGRT0ewpeTPUQfHZonBQDuWwe2fiDP2UmmnAg4/edit) into markdown and add it.

Assigning to @Feanor78 (please review the doc, as well).

**Comment by jsigwart** [comment]
Can I suggest linking it in the footer? There are no legal disclaimers or copyright info on the bottom of the site right now. Need privacy policy, too, but that should be its own issue.

**Comment by kauffj** [comment]
Let's treat that separately https://github.com/lbryio/lbry.io/issues/369

**Comment by tzarebczan** [comment]
@jsigwart can we close this issue?

**Comment by jsigwart** [comment]
Yes, please close.
