### ISSUE TITLE
Add 'Contact Us' page / link or link to email contact

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.io#386]
Currently, when navigating through the main lbry.io pages, there's no easy access to contact information. 

We should:
a) create a contact us page and link to it from main header/footers Page would also have office info/contact phone number? 
or 
b) add email contact button which goes to hello@lbry.io to main header/footers

**Comment by kauffj** [comment]
I support the addition of a public contact email (hello@), but I think putting this in the header is wrong and _probably_ the footer is wrong too. Maybe just on the /learn page?

**Comment by ykris45** [comment]
#390

**Comment by ykris45** [comment]
#390

**Comment by ykris45** [comment]
https://user-images.githubusercontent.com/26609573/36509731-3d10b5d6-1793-11e8-8bf7-5ef9e5528a6a.png
