### ISSUE TITLE
Identify top 404s

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.io#402]
It'd be good to log/track the most common 404s, so we can see if there are redirects or pages that should exist at the accessed URLs.

**Comment by kauffj** [comment]
This is probably in Analytics already.

**Comment by finer9** [comment]
I dont understand how our 404 is served...it seems dynamic?  I dont think there is a special 404 section in typical analytics; you'd just look at the stats for the 404 page, see referrers, etc.  However there may be a custom report that actually parses the log for 404s.  Any thoughts?

**Comment by Smurphonomics** [comment]
This is probably old news now, but... All 404 are found in Google Search Console. under Crawl Errors. :)

**Comment by tzarebczan** [comment]
Closing this. We went through one round and @jsigwart / @finer9 will be tracking monthly.
