### ISSUE TITLE
Download page should be more "expressive"

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry.io#405]
Currently when a user is redirected to the download page with `?auto=1` appended to the URL the download starts automatically, however the download button is still displaying big.
Some sort of animation or at least a change in a label saying something like `Thank you for downloading LBRY` should be displayed instead.

The same should happen when the button is clicked.

An example is found here: https://www.mozilla.org/en-US/firefox/new/

**Comment by alyssaoc** [comment]
closing, will consider as part of the larger redesign
