### ISSUE TITLE
Press kit page has missing picture or broken picture link

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry.io#417]
One of the users reported bad link to a non-working video, I've changed that. Then I noticed that there is a broken pic link to one of the founders:  Jimmy Kiselak.

**Comment by ykris45** [comment]
#418

**Comment by ykris45** [comment]
@tzarebczan can it be closed sir. jimmy kiselax didnt work with lbry team anymore . kauufj say that to mine

**Comment by tzarebczan** [comment]
Thanks @ykris45 !
