### ISSUE TITLE
Email Management 2.0

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.io#422]
(All the items below plus stuff attached to this epic)

1. Create a route, `/list/edit/{token}` that will be used to display and edit a user's email preferences.
2. Call the API endpoint `/user/email_status` to retrieve a user's email settings.
3. Display a form to the user that allows them to edit their settings. This form should work as follows:
    - A radio option that says "Receive No Email" and "Receive Email". This defaults to `user.is_email_enabled`.
   - If "Receive Email" is selected, (up to) two additional sections should fold out below it.
   - If the user has multiple emails, a heading labeled "Enabled Emails" should be displayed, with a checkbox next to each email. If a user has only 1 email, hide this section.
   - A heading labeled "Email Topics", with a bank of checkboxes below it for each possible tag.
4. When submitted, this form should make calls to internal-apis as appropriate. Note that we should only update the options a user explicitly changes. E.g. if they go from "Receive Email" to "Receive No Email", then all of their tags should remain (this way if they enable again, they're in the same groups).

See: https://github.com/lbryio/internal-apis/issues/246

**Comment by kauffj** [comment]
@NetOperatorWibby now that @tiger5226 has done the API work for this this a decent candidate to go near the top of the web list. Please catch up on this ticket and, if you see any issues with the proposed design, raise them ASAP.

**Comment by NetOperatorWibby** [comment]
@kauffj What exactly is this issue referring to? I see no mailing list on the site. What is the URL users would hit to even see this information? Is this supposed to be for the app?

**Comment by NetOperatorWibby** [comment]
Okay `/list/edit/{token}` confused me as a route that'd be on the site. Why not use something like `/subscription-settings/{token}`? It's more descriptive and to the point without (what seems like) unnecessary paths. Currently, it makes me think I'll see something else if I visit `/list`.

How would a user have multiple email addresses? Also, where is the unsubscribe link generated?

**Comment by kauffj** [comment]
@NetOperatorWibby `/list/xxx` matches existing usage, but no strong opinions about naming here.

I believe a user can end up with multiple emails by authenticating multiple times on the same install/device id. 

The unsubscribe link is generated by the internal-apis code. You should be able to see one in any emails you've received from us.
