### ISSUE TITLE
Add more information on get page 

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry.io#424]
it would be better if the download page on get.php shows like the screenshot below so that novice visitors can understand and not in confused with the meaning of the word at the bottom of the download button
![screenshot_2018-03-14-04-07-40-104](https://user-images.githubusercontent.com/26609573/37369945-486eba5e-273d-11e8-86f9-3e8104b2dc89.jpeg)

**Comment by tzarebczan** [comment]
@ykris45 Want to submit a PR for this? It should probably say: "Latest Version"

**Comment by ykris45** [comment]
@tzarebczan ok. on it sir

**Comment by tzarebczan** [comment]
Closed via https://github.com/lbryio/lbry.io/pull/443
