### ISSUE TITLE
Firefox/Chrome dynamic scrolling not working on new youtube page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.io#427]
Logging this for @maximest-pierre in case someone else runs into this issue, but I think it's something locally on my machine. When I click the claim channel button or the scroll up button, nothing happens. It works fine in IE. Also works on my desktop. 've had issues with other sites like design.lbry.io on this machine.

**Comment by maximest-pierre** [comment]
Closing this I haven't seen anybody else have this problem. If someone stumbles on this issue and has this problem you can leave a comment.
