### ISSUE TITLE
Site takes 5-7 seconds to load if AdBlocker EasyPrivacy list is enabled

### ISSUE THREAD

**Issue by IGassmann** [lbryio/lbry.io#478]
If the list [EasyPrivacy](https://easylist.to/) is enabled on the user browser AdBlock (Adblock Plus, AdBlock or uBlock Origin) the website takes about 5-7 seconds to load any page.

**Comment by maximest-pierre** [comment]
This is probably caused by the facebook analytic and Google analytics.

**Comment by alyssaoc** [comment]
closing, this is no longer an issue. repopen if necessary
