### ISSUE TITLE
Redesign/improve home page to give site a more modern/contemporary look

### ISSUE THREAD

**Issue by Feanor78** [lbryio/lbry.io#507]
Redesign the front page of the website to give more visually interesting, modern feel to the site. Change the front page CTA from "download LBRY" to another ask around signing up for development updates, Android, android testing, sign up for updates about new versions, etc.

Bring website in line with visual identity of the app redesign so we're on brand in terms of colors, visual assets, etc.

**Comment by alyssaoc** [comment]
closing, will consider as part of the larger design
