### ISSUE TITLE
Video playing on https://lbry.io/get doesn't feel right

### ISSUE THREAD

**Issue by DiSae** [lbryio/lbry.io#509]
The video playing when browsing to https://lbry.io/get is called 'It's a disaster'. 
I don't want to think that LBRY is a disaster, please choose another video.

**Comment by Smurphonomics** [comment]
Good find. These things do get **subliminally** locked in peoples **subconscious** and can affect their feelings about a product.

Big companies use this in a positive way to sell a product and I also use the technique in my work.

This was obviously not planned but is an important issue that could do with some love <3

![image](https://user-images.githubusercontent.com/29914179/38929654-5fcf7448-4350-11e8-8cac-d8916189884b.png)

https://www.wordstream.com/blog/ws/2017/10/24/subliminal-advertising

**Comment by maximest-pierre** [comment]
This is the line of code that handles that particular gif.
https://github.com/lbryio/lbry.io/blob/master/view/template/download/get.php#L47

Feel free to suggest another gif and change it. 

Also, it needs to be changed to represent the latest version of the app.

**Comment by tzarebczan** [comment]
We'll be updating when the redesign is launched.

It's a Disaster was one of the first major movies released on LBRY, which is why it is showcased on the GIF.

**Comment by tzarebczan** [comment]
The get page gif is now updated.
