### ISSUE TITLE
Refactor API forms to be more DRY and development friendly

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.io#510]

**Comment by maximest-pierre** [comment]
Issue moved to [lbryio/api-forms #18](https://github.com/lbryio/api-forms/issues/18) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lyoshenka** [comment]
Issue moved to [lbryio/api-forms #19](https://github.com/lbryio/api-forms/issues/19) via [**ZenHub**](https://www.zenhub.com/)
