### ISSUE TITLE
Create page for more information concerning DMCA complaints

### ISSUE THREAD

**Issue by IGassmann** [lbryio/lbry.io#512]
Have a page at https://lbry.io/faq/dmca that would give more details concerning DMCA complaints. The app would link this page when it reaches a blocked content.

**Comment by tzarebczan** [comment]
We already have https://lbry.io/faq/content - can we just link there? Or break out the DMCA portion to a separate faq and have a link from /faq/content to it?

**Comment by tzarebczan** [comment]
TODO: 
-  "Someone uploaded my content to LBRY without permission. How do I remove it?" - Change "remove" to "report" and move this question into /dmca article.

- /faq/content should continue to evolve into a more general FAQ about how LBRY handles content, particularly to explain what's different from status quo / traditional systems. It should focus less on the DMCA/takedown side of things and drive people to /dmca for that.

- lbry.io/faq/dmca should explain that we record all DMCA requests we act on in GitHub and link to the rep

**Comment by tzarebczan** [comment]
Completed via https://github.com/lbryio/lbry.io/pull/534
