### ISSUE TITLE
Add 3D file-viewing to LBRY desktop app

### ISSUE THREAD

**Issue by jamesbiller** [lbryio/lbry.io#523]
Link to info & .js https://manu.ninja/webgl-3d-model-viewer-using-three-js/

Needs to operate like the 'Thingiview' in Thingiverse: https://www.thingiverse.com/thing:572581

**Comment by tzarebczan** [comment]
Will move this over to the lbry-app repo. I could have sworn I had an issue open for this already, but I guess not.

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/lbry-app #1409](https://github.com/lbryio/lbry-app/issues/1409) via [**ZenHub**](https://www.zenhub.com/)
