### ISSUE TITLE
Add search bar on website

### ISSUE THREAD

**Issue by DiSae** [lbryio/lbry.io#529]
If possible, please add a search bar on the website.
The below link may help to start the coding.
https://stackoverflow.com/questions/21663842/adding-a-search-bar-in-my-website-with-php?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

![lbc search website](https://user-images.githubusercontent.com/31828724/39486398-42ce20c0-4d7c-11e8-98fb-f6622438c4f5.png)

**Comment by tzarebczan** [comment]
Thanks for the suggestion, we'll see what we can do! Since we have a bunch of higher priority items at the moment, we may not get around to this immediately.

**Comment by alyssaoc** [comment]
closing, we will not be adding search
