### ISSUE TITLE
lbry.io mobile version issue

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry.io#531]
There is an issue on the mobile version of the website, at the very lower button, below the what's next, the Get LBRY button is separated, making the LBRY barely visible. 
Url https://lbry.io/news/lbry-development-community-update-mar-2018

**Comment by tzarebczan** [comment]
@ceoger thanks for filing this, sent you a few LBC on Discord :)

**Comment by ykris45** [comment]
#715

**Comment by ykris45** [comment]
@tzarebczan close close... hehehe.
