### ISSUE TITLE
400 error in verification process with google

### ISSUE THREAD

**Issue by DaniNz** [lbryio/lbry.io#572]
On the [verification page](https://verify.lbry.io/index.php) in step 1 ( Link Your Social Networks), when I click on google it redirects me to a 400 error page.
![screenshot from 2018-05-23 20 39 50](https://user-images.githubusercontent.com/16692007/40457689-321ff042-5ece-11e8-9cb1-6236b83ffa83.png)

**Comment by tzarebczan** [comment]
Thanks for filing this, I reached back out on Discord. We'll take a look at the Auth process. 

I see you already have the contributing doc up 😂

**Comment by tzarebczan** [comment]
This is now fixed, thanks again!

**Comment by tzarebczan** [comment]
It only gets added once you verify with one of the social networks.

**Comment by DaniNz** [comment]
Got it, works for me!
