### ISSUE TITLE
Empty press kit .zip file

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry.io#579]
The .zip file in https://lbry.io/press-kit is empty. Several people tested it and it contains no files.

**Comment by maximest-pierre** [comment]
I just tried it on Ubuntu with chrome(65.0.3325.181) and Firefox (60.0.1) and the zip contains the correct files.

**Comment by maximest-pierre** [comment]
It seems that the problem lies with open the zip with windows explorer

**Comment by LavRadis** [comment]
It does not work on my Win10, kcSeb also cannot open it, and one other guy in discord. Looks like we all use Win 10.

**Comment by LavRadis** [comment]
It works when I open it with WinRAR.

**Comment by maximest-pierre** [comment]
I suspect its something with the encoding
