### ISSUE TITLE
Youtube onboard accepts underscores

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry.io#581]
The youtube onboard program accepts underscores for the field "LBRY Channel ID" (which ideally should spell out Desired LBRY Channel Name).
This causes ytsync to fail because it can't publish claims with underscores. Please limit it with the right regex.

(this should be also limited in internal-apis)

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry.io/commit/bca2215faf8eb8b1a57a263d8f65c9e0534d7735 / https://github.com/lbryio/lbry.io/commit/1cc2ecb3b1e557c394e88fb211c677520c370688
