### ISSUE TITLE
Move the Optimize Page-Hiding Snippet to the head

### ISSUE THREAD

**Issue by Krisseck** [lbryio/lbry.io#597]
When I open any lbry.io page, I get the following effect:
- Top of the page loads normally
- Page changes to all white
- Page loads normally again

This happens in a span of 1-2 seconds, creating a flashing effect every time I change the page.

The issue is that the [Optimize Page-Hiding Script](https://developers.google.com/optimize/) you are using is at the bottom of the website, so it takes a while when the browser reaches that part of the page and renders the all white website. You should move this piece of code to the head section so it loads faster.

**Comment by kauffj** [comment]
@Krisseck I gave you write access to this repo.

The relevant files are:
- https://github.com/lbryio/lbry.io/blob/master/view/template/layout/basic.php (used by basically all pages on the website)
- https://github.com/lbryio/lbry.io/blob/master/view/template/layout/_analytics.php (included by layout.php and includes all JS analytics assets)

**Comment by kauffj** [comment]
Commits to master will automatically deploy to the live site, no other deploy steps are required.
