### ISSUE TITLE
Large Page Sizes Harming SEO and User Experience.

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry.io#631]
## SEO and User Experience

On various pages, images are being called in which are extremely **large**.

As an example, the [Team Page](https://lbry.io/team) is a whopping **12.3MB** in size. This is due to images being pulled in from [spee.ch](https://spee.ch/@lbryteam:6/josh-finer.jpg) that are **not** formatted for the web. The team images should be no more than **60kb** each, not **3mb**.

[Page speed](https://gtmetrix.com/reports/lbry.io/WsRP3C4J) is one of the most important metrics for search engines when determining if you are a good page to display in search results. Furthermore, a slow loading website will have a high [bounce rate](https://en.ryte.com/wiki/Bounce_Rate).

## People expect sites to loads in two seconds
Two studies by Akamai and Gomez are frequently cited in reports into site speed, although both are several years old now so it’s likely that web users’ expectations are even higher now.

A recent Google/SOASTA Research confirms that slow pages increase bounces, moreover it spoils the first impression, so one hardly ever comes back to your page.

[Read more](https://econsultancy.com/blog/10936-site-speed-case-studies-tips-and-tools-for-improving-your-conversion-rate)

***The file size/speed issues need to be addressed in the new design.**

## Speed Statistics for Team Page

![image](https://user-images.githubusercontent.com/29914179/41448558-98ebb4d2-709e-11e8-8a6a-b90ae2eb7d1a.png)

![image](https://user-images.githubusercontent.com/29914179/41448642-2a7bd490-709f-11e8-94a6-49628e9ac691.png)

![image](https://user-images.githubusercontent.com/29914179/41448699-9f6c2b10-709f-11e8-9f83-ee0d25523e8f.png)

**Comment by kauffj** [comment]
Bleh :/

Probably going to wait for spee.ch editing to fix this.

I would say that page score over-estimates the problem, since it's just images loading the page is already rendering and interactable. Loading problems that prevent interaction are much worse in terms of bounces.

**Comment by kauffj** [comment]
It looks like the especially large ones weren't even sized correctly in the first place.

**Comment by Invariant-Change** [comment]
Easy fix - Do you want to make some resized, web-ready images to replace current ones?

**Comment by Invariant-Change** [comment]
So that everything that links back to them still finds them? That makes sense.

**Comment by alyssaoc** [comment]
Closing, no longer an issue. page loads quickly

**Comment by tzarebczan** [comment]
This is still an issue as the spee.ch assets are really large and pages take a while to load on slower connections. I think the fix is to edit the spee.ch assets with optimized ones once we have that functionality in place in prod spee.ch

**Comment by kauffj** [comment]
Marked the dependency. Once https://github.com/lbryio/spee.ch/issues/482 is fixed, can you resize these @tzarebczan?

**Comment by alyssaoc** [comment]
@Feanor78 We can talk about the path forward here

**Comment by finer9** [comment]
Analytics does this too. Last time I looked our popular page loads were
almost 10s which is pretty high

**Comment by tzarebczan** [comment]
We are at 67% now, and all the images are showing the correct smaller sizes, going to close: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Flbry.io%2Fteam

**Comment by Invariant-Change** [comment]
# PAGE SPEED

Results seem to vary, I got this on first run with Google, then subsequent tests usually got around 62.

![image](https://user-images.githubusercontent.com/29914179/52058531-611a5480-25b3-11e9-9f30-31c1df5eb0f2.png)

## GOING INTO DETAIL

I ran a more detailed test and compiled a report (see PDF) which can be useful for optimising the site to perform better:

**Online summary report:** https://gtmetrix.com/reports/lbry.io/yFwITTVJ

**Full report:** [GTmetrix-report-lbry.io-full.pdf](https://github.com/lbryio/lbry.io/files/2817468/GTmetrix-report-lbry.io-full.pdf)
