### ISSUE TITLE
Misidentifying ChromeOS as MacOS

### ISSUE THREAD

**Issue by ocornoc** [lbryio/lbry.io#639]
On the homepage, my Chromebook is misidentified as having macOS as the operating system, where it should be Linux (in the case of someone using the popular https://github.com/dnschneid/crouton in order to have a usable Linux environment on ChromeOS).

![screenshot 2018-06-16 at 2 50 12 pm](https://user-images.githubusercontent.com/25855126/41502860-6f1acdd4-7178-11e8-9646-3f3c8dfa1e3a.png)

**Comment by alyssaoc** [comment]
closing, tested and this is not longer an issue

**Comment by naturallymitchell** [comment]
this issue still exists for me
