### ISSUE TITLE
captcha not hidden after verifying

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.io#644]
Looks like some work was done here: https://github.com/lbryio/lbry.io/pull/323 but it still shows after verifying - goes back to captcha screen and shows that verification has expired. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
@tzarebczan is this still valid?

**Comment by tzarebczan** [comment]
Nope, this no longer happens.
