### ISSUE TITLE
Embed Tweets for all TipBot commands

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.io#676]
Update [this article](https://lbry.io/faq/tipbot-twitter) to include embedded tweets for all commands. The embedded tweets should not replace the commands, both should be shown.

**Comment by kauffj** [comment]
@ykris45 good one for you?

**Comment by ykris45** [comment]
@kauffj i will do it . stay awake for this night sir

**Comment by ykris45** [comment]
@kauffj im done my boss

**Comment by ykris45** [comment]
@kauffj or @tzarebczan close close close...

**Comment by tzarebczan** [comment]
Thanks again Chris, sent you a tip on Discord.
