### ISSUE TITLE
Support existing LBRY publisher on /youtube signup flow

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.io#684]
In order to support existing LBRY creators who migrate to YouTube Sync (non-public/internal api issue - https://github.com/lbryio/internal-apis/issues/471), we would need to capture additional data like their channel signing certificate (needs to be transferred/stored securely) and wallet address to start publishing their content automatically.  

@alyssaoc we may want to create an epic (or turn this issue into an epic) if and when we are ready to spec it out.

**Comment by alyssaoc** [comment]
Issue moved to [lbryio/ytsync #1](https://github.com/lbryio/ytsync/issues/1) via [**ZenHub**](https://www.zenhub.com/)
