### ISSUE TITLE
iOS bounty page doesn't exist...

### ISSUE THREAD

**Issue by NetOperatorWibby** [lbryio/lbry.io#690]
...but is referenced on `lbry.tech`.

### Issue on the .tech repo:
https://github.com/lbryio/lbry.tech/issues/126

### The Markdown file mentioning the bounty: (scroll to iOS Applications)
https://github.com/lbryio/lbry.tech/blob/master/documents/build.md

### Live link to page:
https://lbry.tech/build

**Comment by tzarebczan** [comment]
Closing per https://github.com/lbryio/lbry.tech/issues/126#issuecomment-409258604
