### ISSUE TITLE
Make top icons match bottom icons  

### ISSUE THREAD

**Issue by jamesbiller** [lbryio/lbry.io#698]
The icons that we have at the top of the lbry.io pages should match those that we have at the bottom on the lbry.io/get page.

<img width="652" alt="screen shot 2018-08-06 at 9 57 08 am" src="https://user-images.githubusercontent.com/38798392/43720946-82aabec2-995f-11e8-8ba2-34a4589012fc.png">

Those^

Should also be here:

![image](https://user-images.githubusercontent.com/38798392/43720963-8dbcc30a-995f-11e8-8d29-1b5cd0cb87ad.png)

**Comment by ykris45** [comment]
i referenced issues no #703

**Comment by tzarebczan** [comment]
@kauffj / @jsigwart do you recall if this was done on purpose? I think the original intent was to put the less important ones in the footer and keep the header clean. If not, then we can merge https://github.com/lbryio/lbry.io/pull/703

**Comment by ykris45** [comment]
@tzarebczan or should adding faq to header. most of website added faq to the header formake visitor easily to read that

**Comment by jsigwart** [comment]
We should revisit this with lbry.io redesign and think about navigations and usability. We certainly don't want the top navigation getting too complex.

**Comment by ykris45** [comment]
@kauffj what do you think if add FAQ to header Sir?

**Comment by jamesbiller** [comment]
@jsigwart I kinda like how Dfinity does the icons on the side and then at the bottom
<img width="1334" alt="screen shot 2018-08-11 at 12 26 23 pm" src="https://user-images.githubusercontent.com/38798392/43993860-ee1e321e-9d61-11e8-9ba1-1c84cdccd69a.png">
<img width="1348" alt="screen shot 2018-08-11 at 12 26 34 pm" src="https://user-images.githubusercontent.com/38798392/43993861-ee2b93fa-9d61-11e8-9808-8e2ae1c8dde0.png">

**Comment by jsigwart** [comment]
We have a funny thing going on where sometimes the social media icons take you to our social media sites and other times (like on news pages), they're used to share the post on social media.

**Comment by ykris45** [comment]
@tzarebczan maybe the PR #703 should solve this issues. and i think its only temporary until redesign finished.

**Comment by alyssaoc** [comment]
closing, the redesign will fix this
