### ISSUE TITLE
Quicker full unsub from new email management page

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.io#723]
The new email management page at `/list/edit/{foo}` is much better, but it lacks a way for someone to quickly never receive a message again. It's important that we still support this while still encouraging users to opt out of messages they no longer want to receive.

**Comment by tiger5226** [comment]
@kauffj Is this really a required issue for email management 2.0? Most users only have 1 email address and clicking the toggle for receiving email accomplishes this for all users that have 1 email address. If they have 2, then its two toggles.

**Comment by tiger5226** [comment]
As an FYI this can be achieved by calling the api n times once for each email. 

`/user/email/edit?email=<email>&auth_token=<token>&is_enabled=<true/false>`

The above allows a user to unsubscribe from all emails for the email address. Most users should have just 1 email but to make it easier for users with multiple emails, we can just add a button that handles this process for 1 or n emails. 

@kauffj - you just wanted a toggle for "everything"

**Comment by kauffj** [comment]
@tiger5226 can you fix the JS bug we found and @NetOperatorWibby can handle any remaining style changes?

**Comment by NetOperatorWibby** [comment]
Just let me know when you’re done @tiger5226!

**Comment by tiger5226** [comment]
@NetOperatorWibby It is all yours! It has been merged in.
