### ISSUE TITLE
Add social share icon for LBRY FAQ

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry.io#727]
currently LBRY Have social share button on the news section. would be nice this feature available on FAQ Section. because if another user ask on twitter and facebook or whatsapp messager about how to solve issues on LBRY App instead . user can share the FAQ Article via the share button

**Comment by tzarebczan** [comment]
Good idea, but it's also fairly easy to share from the URL. I don't see many people sharing directly to social media from a FAQ article.
