### ISSUE TITLE
"Magic link" page needs better how-to for Android

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.io#765]
@LavRadis commented on [Mon Sep 17 2018](https://github.com/lbryio/lbry-android/issues/300)

## The Issue

"Magic link" confirmation link makes Android offer to open LBRY app OR Coinomi (since the also registered for lbry://). The page needs a better how-to explanation for the new user to reduce confusion and number of people who will choose to open with Coinomi. 

---

@tzarebczan commented on [Mon Sep 17 2018](https://github.com/lbryio/lbry-android/issues/300#issuecomment-422103081)

I originally thought this note might be better on the Android app, but agree that it makes more sense ont he verification page. Will move this over to lbry.io.

**Comment by kauffj** [comment]
Why is coinomi registering as a schema handler for `lbry://`?

**Comment by kauffj** [comment]
There is at least an Android issue here as well, in that it should notify on open and install if another app has `lbry://`

**Comment by tzarebczan** [comment]
Looks like they do this to support payments for other coins as well: https://github.com/Coinomi/coinomi-android/blob/master/core/src/main/java/com/coinomi/core/uri/CoinURI.java 

Will re-open the Android issue to discuss your last point. Maybe it can prompt the LBRY to make it default for lbry://
