### ISSUE TITLE
Update photo on LBRY.io/team

### ISSUE THREAD

**Issue by Feanor78** [lbryio/lbry.io#779]
Update the banner photo on the Team page

**Comment by kauffj** [comment]
Needs to be updated in two places:

https://github.com/lbryio/lbry.io/blob/master/view/template/page/team.php#L6
https://github.com/lbryio/lbry.io/blob/master/view/template/page/team.php#L2 (when embedded)

Please replace with a spee.ch URL when updating

**Comment by tzarebczan** [comment]
@Feanor78 / @jsigwart can you find a good team photo it can be updated with?
