### ISSUE TITLE
Typo found

### ISSUE THREAD

**Issue by faraicelebr8** [lbryio/lbry.io#808]
I would like to report a typo on your latest article: "Development Update Aug/Sept 2018" by Tom Zarebczan posted on Oct 5 2018.  https://lbry.io/news/sept-dev-update

The typo is found in the second sentence of the opening paragraph where the word "**begging**" was used instead of "**beginning**" - see  below:

> _"... As you may have read in our Aug/Sept Community update, we are splitting up our monthly reports into two - one in the middle of the month for community updates and one at the **begging**/end of the month for development..."_

**Comment by tzarebczan** [comment]
Feel free to submit a pr to fix it and you can earn some LBRY!

**Comment by ykris45** [comment]
@faraicelebr8 https://github.com/lbryio/lbry.io/edit/master/content/news/187-sept-dev-update.md please submit a PR on this link

**Comment by jasoncarle** [comment]
Hi guys, I've just submitted a PR for the typo fix:
https://github.com/lbryio/lbry.io/pull/809

cheers
