### ISSUE TITLE
Typo in FAQ Basics

### ISSUE THREAD

**Issue by gilbertoesp** [lbryio/lbry.io#811]
lbry.io/content/faq/lbry-basics.md under fisrts images, there is a markdown typo, in the link

**Comment by tzarebczan** [comment]
Where exactly is it? Feel free to submit a pr to fix it.

**Comment by ykris45** [comment]
#812 i fixed it

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry.io/pull/812.

Thanks for the heads up @gilbertoesp !
