### ISSUE TITLE
Generate analytics IDs server-side

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.io#854]
For any 3rd-party platforms that we use to generate users or need analytics from, we should switch to server-side generation of IDs.

- [GA](https://support.google.com/analytics/answer/3123666) 
- [FB](https://developers.facebook.com/docs/analytics/properties#js)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
1) This question prompted me to consider if it would make sense to just have internal-apis do this, since that'd ease using it across our web properties. The site doesn't really have a data model currently or a concept of a user, which is where I'd typically be inclined to put it. `Session`  is probably closed.

2) Yes, that is the template that would be changed to modify the way we pass the new analytics user id.

3) Yes.

4) Flashes refer to special session values that will only persist for one subsequent request, unless that request calls `Session::persistFlashes()`. No flashes are automatically rendered.

5) Yes, those calls and potentially 1 or 2 other places need to be updated as well. Just do a search for `ga(`.

**Comment by tiger5226** [comment]
Jeremy I started working on the PHP side of the web visitor logging last night. It wound up being really simple. So simple it makes me question whether I was doing it right. I pushed a branch but I would like you to take a quick look. The easy solution was to use the session_id generated by the session class already and push those to google analytics and facebook pixel. Then for each page access in the analytics footer I call the web visitor logging api with the ip address. I tested this out last night and it works great. I was able to link my internal-apis account easily. I was thinking that we could even take it one step further and when I call the web logging API and I have a linked user_id I can set that as the user_id for google and facebook. This way we are tracking not only across sessions but for weeks and months. Going to also put this on the issue.

**Comment by tiger5226** [comment]
A few things I could not do last night. I wanted to test that the `ga` and `fbq` calls worked. I trace the code and found the config setup for the site and adjust the `IS_PROD` config parameter but it would not work. I also adjusted the PHP if/else to be `true` and it still did not do it. I was check the page source to see if the javascript was written to the bottom of the page and it was still the "this is not a prod environment message". Is there an easy way to test this as prod?

**Comment by kauffj** [comment]
@tiger5226 

1) Your branch looks good, other than whether it's appropriate to generate these user ids on the web server. Since users may also (eventually) get generated via lbry.tech, open.lbry.io, or other properties, I think it may be better to let internal-apis generate a web visitor id rather than each web property doing it.

2) I'm not sure why you were unable to test. [This line](https://github.com/lbryio/lbry.io/blob/master/web/index.php#L10) sets the `IS_PRODUCTION` value. If you were literally changing the statement to `if (true)`, I don't see how the code could fail to execute? Something else must be up.

**Comment by kauffj** [comment]
>  I was thinking that we could even take it one step further and when I call the web logging API and I have a linked user_id I can set that as the user_id for google and facebook. This way we are tracking not only across sessions but for weeks and months.

This is a good idea.

**Comment by tiger5226** [comment]
merged and deployed
