### ISSUE TITLE
Change sourcing of roadmap to GitHub

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.io#914]
Our 2019 goals are going to be sourced from GitHub, not Asana.

(@tzarebczan FYI)

**Comment by ykris45** [comment]
@kauffj can i help to change asana to github for fixing this issues ?.. maybe @tzarebczan can collaborate with me again to opening my 2019 contribution on this ecosystem...

**Comment by tzarebczan** [comment]
@ykris45 sorry for not responding earlier and thanks for trying to help. I'm not sure exactly what the plan on sourcing these from GitHub are, need to find out more from @kauffj / @lyoshenka . Do we have a timeline for this and who is implementing it?

**Comment by kauffj** [comment]
Will be discussed on upcoming web planning meeting. 

I can probably do this somewhat quickly (1-1.5hrs?), but we might want to just wait for the redesign to be done?
