### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry.io#918]
I was able to get Xdebug compiled and used against the website. 90% + of our web page load times are in the following two methods:

https://github.com/lbryio/lbry.io/blob/fdea49e153129159bfed2bcb4794cb6225240bb8/autoload.php#L23-L48

Here the problematic area is the `OS::GetAll` and the `YAMLLoadString`

https://github.com/lbryio/lbry.io/blob/b6968240822771b3e03d4cdcfc8d44d42bff3a8e/controller/Controller.class.php#L76-L149

Here the problematic area is the `RecursiveIteratorIterator`. 

I am ignoring the compile css since that does not happen in production. See the profile screenshot below:

<img width="1262" alt="screen shot 2019-01-08 at 10 40 12 pm" src="https://user-images.githubusercontent.com/3402064/50875446-69a5b380-1396-11e9-8d77-6fe592067948.png">

The profile is [here](https://files.slack.com/files-pri/T1R0NMRN3-FFAJRET63/download/cachegrind.out.91312)

The next biggest cost is the rendering of the view. @kauffj From our other discussions, it sounded like this should always be at the top of the costs. It is so small compared to the other two. Maybe we can have some really quick and REALLY substantial wins here from this investigation.

**Comment by kauffj** [comment]
`Autoload::reload` should not be getting called in production. Unless the APC check is failing, I don't understand how anytime could be spent in the autoloader in production. Similarly, `View::compileCss` should not be happening in production. (Aside from the first execution after a deploy, which is also true for autoloading).

**Comment by tiger5226** [comment]
Thanks for taking a look Jeremy. I did a new profile with is prod turned on in the config but after the first call. And the total time dropped down to 350ms. Closing for now.
