### ISSUE TITLE
Allow deleting content from Downloads page

### ISSUE THREAD

**Issue by kingofmen** [lbryio/lbry.io#963]
#### Issue Summary

The app FAQ states that content can be downloaded from the Downloads menu, thus:

> Currently, there is no way to stop sharing or to store data temporarily, but you can always delete any files you don't want to seed from the LBRY app "Downloads" menu. 

but this does not seem to be correct, as shown in the attached screenshot - there is no delete button for the downloads, unless I am missing something. At the very least it is not obvious to me, and I did poke around a bit.

![lbrybug](https://user-images.githubusercontent.com/1146923/52894425-eb3eed00-315d-11e9-828d-ec6b6026bfaf.png)

#### Steps to Reproduce

1. Go to Downloads menu in the app.
2. Observe the lack of a Delete button.

There are two obvious ways to fix this - either add the delete button, or change the FAQ to report the correct way of deleting downloaded content. Which seems to be to go to the streams, one by one, and click the delete button there; I observe that this is not very user-friendly for mass deletions. A _good_ fix will add some tools for bulk management - at the very least "select all", possibly some nice filtering options.

**Comment by tzarebczan** [comment]
Hey, thanks for the issue . The correct place to file would be https://GitHub.com/LBRYio/LBRY-desktop

We have a similar issue filed there already, closing this one for now.

Please check out LBRY.tech for a tech overview of you plan to contribute ;)

**Comment by kingofmen** [comment]
Oh, sorry, my bad. :(

**Comment by tzarebczan** [comment]
No worries!! https://github.com/lbryio/lbry-desktop/issues/1394
